propel:
    database:
        connections:
            default:
                adapter: sqlite
                dsn: sqlite:api/2buy.db
                user: root
                password:
                settings:
                    charset: utf8
