-- MySQL Script generated by MySQL Workbench
-- 09/30/14 14:12:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shoppinglist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `idCommunity` INT(11) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(16) NOT NULL,
  `receiveUpdates` TINYINT(1) NOT NULL DEFAULT '0',
  `receiveSms` TINYINT(1) NOT NULL DEFAULT '0',
  `isAdmin` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idUser`),
  INDEX `fk_user_community1_idx` (`idCommunity` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `community`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `community` ;

CREATE TABLE IF NOT EXISTS `community` (
  `idCommunity` INT(11) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `admin` INT(11) NOT NULL,
  PRIMARY KEY (`idCommunity`),
  INDEX `fk_community_user_idx` (`admin` ASC),
  CONSTRAINT `fk_community_user`
    FOREIGN KEY (`admin`)
    REFERENCES `user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product` ;

CREATE TABLE IF NOT EXISTS `product` (
  `idProduct` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `addedBy` INT(11) NULL DEFAULT NULL,
  `inSuggestions` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idProduct`),
  UNIQUE INDEX `name` (`name` ASC),
  INDEX `addedBy` (`addedBy` ASC),
  CONSTRAINT `product_ibfk_1`
    FOREIGN KEY (`addedBy`)
    REFERENCES `user` (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `remember_me_token`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `remember_me_token` ;

CREATE TABLE IF NOT EXISTS `remember_me_token` (
  `idToken` INT(11) NOT NULL,
  `idUser` INT(11) NOT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `ip` VARCHAR(45) NULL DEFAULT NULL,
  `userAgent` VARCHAR(150) NULL DEFAULT NULL,
  `timestampCreated` TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY (`idToken`),
  INDEX `fk_remember_me_token_user1_idx` (`idUser` ASC),
  CONSTRAINT `fk_remember_me_token_user1`
    FOREIGN KEY (`idUser`)
    REFERENCES `user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transaction` ;

CREATE TABLE IF NOT EXISTS `transaction` (
  `idTransaction` INT(11) NOT NULL AUTO_INCREMENT,
  `idProduct` INT(11) NOT NULL,
  `reportedBy` INT(11) NOT NULL,
  `reportedDate` DATETIME NOT NULL,
  `editedBy` INT(11) NULL DEFAULT NULL,
  `amount` INT(11) NOT NULL,
  `boughtBy` INT(11) NULL DEFAULT NULL,
  `cancelled` TINYINT(1) NOT NULL DEFAULT '0',
  `cancelledBy` INT(11) NULL DEFAULT NULL,
  `closeDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idTransaction`),
  INDEX `reportedBy` (`reportedBy` ASC),
  INDEX `boughtBy` (`boughtBy` ASC),
  INDEX `idProduct` (`idProduct` ASC),
  INDEX `cancelledBy` (`cancelledBy` ASC),
  INDEX `editedBy` (`editedBy` ASC),
  CONSTRAINT `transaction_ibfk_1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `product` (`idProduct`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_ibfk_2`
    FOREIGN KEY (`reportedBy`)
    REFERENCES `user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_ibfk_3`
    FOREIGN KEY (`boughtBy`)
    REFERENCES `user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_ibfk_4`
    FOREIGN KEY (`cancelledBy`)
    REFERENCES `user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `transaction_ibfk_5`
    FOREIGN KEY (`editedBy`)
    REFERENCES `user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
